# docker-compose.yml

#!/bin/bash
set -e

# Clean up any existing containers
docker-compose down --remove-orphans

# Start the services with a timeout
echo "Starting services..."
timeout 300 docker-compose up -d || {
    echo "❌ Services failed to start within 5 minutes"
    echo "=== Database Logs ==="
    docker-compose logs db
    echo "=== Web Logs ==="
    docker-compose logs web
    exit 1
}

# Wait a bit more and verify services are running
sleep 10

# Check if containers are healthy
if docker-compose ps | grep -q "unhealthy\|Exit"; then
    echo "❌ Some services are not healthy"
    docker-compose ps
    docker-compose logs
    exit 1
fi

echo "✅ Services started successfully!"

# Optional: Test the application
if command -v curl &> /dev/null; then
    echo "Testing application..."
    for i in {1..30}; do
        if curl -f http://localhost:8082/ > /dev/null 2>&1; then
            echo "✅ Application is responding!"
            break
        fi
        echo "⏳ Waiting for application to respond... (attempt $i/30)"
        sleep 2
        if [ $i -eq 30 ]; then
            echo "❌ Application failed to respond after 60 seconds"
            docker-compose logs web
            exit 1
        fi
    done
fi
